<?php

namespace Takaden\Helpers;

class Currency
{
    public static array $currencies = [
        'AFN' => [
            'code' => 'AFN',
            'name' => 'Afghani',
            'entity' => 'AFGHANISTAN',
            'numeric_code' => 971,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'ÅLAND ISLANDS',
            'numeric_code' => 978,
        ],
        'ALL' => [
            'code' => 'ALL',
            'name' => 'Lek',
            'entity' => 'ALBANIA',
            'numeric_code' => 8,
        ],
        'DZD' => [
            'code' => 'DZD',
            'name' => 'Algerian Dinar',
            'entity' => 'ALGERIA',
            'numeric_code' => 12,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'AMERICAN SAMOA',
            'numeric_code' => 840,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'ANDORRA',
            'numeric_code' => 978,
        ],
        'AOA' => [
            'code' => 'AOA',
            'name' => 'Kwanza',
            'entity' => 'ANGOLA',
            'numeric_code' => 973,
        ],
        'XCD' => [
            'code' => 'XCD',
            'name' => 'East Caribbean Dollar',
            'entity' => 'ANGUILLA',
            'numeric_code' => 951,
        ],
        null => [
            'code' => null,
            'name' => 'No universal currency',
            'entity' => 'ANTARCTICA',
            'numeric_code' => null,
        ],
        'XCD' => [
            'code' => 'XCD',
            'name' => 'East Caribbean Dollar',
            'entity' => 'ANTIGUA AND BARBUDA',
            'numeric_code' => 951,
        ],
        'ARS' => [
            'code' => 'ARS',
            'name' => 'Argentine Peso',
            'entity' => 'ARGENTINA',
            'numeric_code' => 32,
        ],
        'AMD' => [
            'code' => 'AMD',
            'name' => 'Armenian Dram',
            'entity' => 'ARMENIA',
            'numeric_code' => 51,
        ],
        'AWG' => [
            'code' => 'AWG',
            'name' => 'Aruban Florin',
            'entity' => 'ARUBA',
            'numeric_code' => 533,
        ],
        'AUD' => [
            'code' => 'AUD',
            'name' => 'Australian Dollar',
            'entity' => 'AUSTRALIA',
            'numeric_code' => 36,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'AUSTRIA',
            'numeric_code' => 978,
        ],
        'AZN' => [
            'code' => 'AZN',
            'name' => 'Azerbaijan Manat',
            'entity' => 'AZERBAIJAN',
            'numeric_code' => 944,
        ],
        'BSD' => [
            'code' => 'BSD',
            'name' => 'Bahamian Dollar',
            'entity' => 'BAHAMAS (THE)',
            'numeric_code' => 44,
        ],
        'BHD' => [
            'code' => 'BHD',
            'name' => 'Bahraini Dinar',
            'entity' => 'BAHRAIN',
            'MinorUnit' => '3',
            'numeric_code' => 48,
        ],
        'BDT' => [
            'code' => 'BDT',
            'name' => 'Taka',
            'entity' => 'BANGLADESH',
            'numeric_code' => 50,
        ],
        'BBD' => [
            'code' => 'BBD',
            'name' => 'Barbados Dollar',
            'entity' => 'BARBADOS',
            'numeric_code' => 52,
        ],
        'BYN' => [
            'code' => 'BYN',
            'name' => 'Belarusian Ruble',
            'entity' => 'BELARUS',
            'numeric_code' => 933,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'BELGIUM',
            'numeric_code' => 978,
        ],
        'BZD' => [
            'code' => 'BZD',
            'name' => 'Belize Dollar',
            'entity' => 'BELIZE',
            'numeric_code' => 84,
        ],
        'XOF' => [
            'code' => 'XOF',
            'name' => 'CFA Franc BCEAO',
            'entity' => 'BENIN',
            'MinorUnit' => '0',
            'numeric_code' => 952,
        ],
        'BMD' => [
            'code' => 'BMD',
            'name' => 'Bermudian Dollar',
            'entity' => 'BERMUDA',
            'numeric_code' => 60,
        ],
        'INR' => [
            'code' => 'INR',
            'name' => 'Indian Rupee',
            'entity' => 'BHUTAN',
            'numeric_code' => 356,
        ],
        'BTN' => [
            'code' => 'BTN',
            'name' => 'Ngultrum',
            'entity' => 'BHUTAN',
            'numeric_code' => 64,
        ],
        'BOB' => [
            'code' => 'BOB',
            'name' => 'Boliviano',
            'entity' => 'BOLIVIA (PLURINATIONAL STATE OF)',
            'numeric_code' => 68,
        ],
        'BOV' => [
            'code' => 'BOV',
            'name' => 'Mvdol',
            'entity' => 'BOLIVIA (PLURINATIONAL STATE OF)',
            'numeric_code' => 984,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'BONAIRE, SINT EUSTATIUS AND SABA',
            'numeric_code' => 840,
        ],
        'BAM' => [
            'code' => 'BAM',
            'name' => 'Convertible Mark',
            'entity' => 'BOSNIA AND HERZEGOVINA',
            'numeric_code' => 977,
        ],
        'BWP' => [
            'code' => 'BWP',
            'name' => 'Pula',
            'entity' => 'BOTSWANA',
            'numeric_code' => 72,
        ],
        'NOK' => [
            'code' => 'NOK',
            'name' => 'Norwegian Krone',
            'entity' => 'BOUVET ISLAND',
            'numeric_code' => 578,
        ],
        'BRL' => [
            'code' => 'BRL',
            'name' => 'Brazilian Real',
            'entity' => 'BRAZIL',
            'numeric_code' => 986,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'BRITISH INDIAN OCEAN TERRITORY (THE)',
            'numeric_code' => 840,
        ],
        'BND' => [
            'code' => 'BND',
            'name' => 'Brunei Dollar',
            'entity' => 'BRUNEI DARUSSALAM',
            'numeric_code' => 96,
        ],
        'BGN' => [
            'code' => 'BGN',
            'name' => 'Bulgarian Lev',
            'entity' => 'BULGARIA',
            'numeric_code' => 975,
        ],
        'XOF' => [
            'code' => 'XOF',
            'name' => 'CFA Franc BCEAO',
            'entity' => 'BURKINA FASO',
            'MinorUnit' => '0',
            'numeric_code' => 952,
        ],
        'BIF' => [
            'code' => 'BIF',
            'name' => 'Burundi Franc',
            'entity' => 'BURUNDI',
            'MinorUnit' => '0',
            'numeric_code' => 108,
        ],
        'CVE' => [
            'code' => 'CVE',
            'name' => 'Cabo Verde Escudo',
            'entity' => 'CABO VERDE',
            'numeric_code' => 132,
        ],
        'KHR' => [
            'code' => 'KHR',
            'name' => 'Riel',
            'entity' => 'CAMBODIA',
            'numeric_code' => 116,
        ],
        'XAF' => [
            'code' => 'XAF',
            'name' => 'CFA Franc BEAC',
            'entity' => 'CAMEROON',
            'MinorUnit' => '0',
            'numeric_code' => 950,
        ],
        'CAD' => [
            'code' => 'CAD',
            'name' => 'Canadian Dollar',
            'entity' => 'CANADA',
            'numeric_code' => 124,
        ],
        'KYD' => [
            'code' => 'KYD',
            'name' => 'Cayman Islands Dollar',
            'entity' => 'CAYMAN ISLANDS (THE)',
            'numeric_code' => 136,
        ],
        'XAF' => [
            'code' => 'XAF',
            'name' => 'CFA Franc BEAC',
            'entity' => 'CENTRAL AFRICAN REPUBLIC (THE)',
            'MinorUnit' => '0',
            'numeric_code' => 950,
        ],
        'XAF' => [
            'code' => 'XAF',
            'name' => 'CFA Franc BEAC',
            'entity' => 'CHAD',
            'MinorUnit' => '0',
            'numeric_code' => 950,
        ],
        'CLP' => [
            'code' => 'CLP',
            'name' => 'Chilean Peso',
            'entity' => 'CHILE',
            'MinorUnit' => '0',
            'numeric_code' => 152,
        ],
        'CLF' => [
            'code' => 'CLF',
            'name' => 'Unidad de Fomento',
            'entity' => 'CHILE',
            'MinorUnit' => '4',
            'numeric_code' => 990,
        ],
        'CNY' => [
            'code' => 'CNY',
            'name' => 'Yuan Renminbi',
            'entity' => 'CHINA',
            'numeric_code' => 156,
        ],
        'AUD' => [
            'code' => 'AUD',
            'name' => 'Australian Dollar',
            'entity' => 'CHRISTMAS ISLAND',
            'numeric_code' => 36,
        ],
        'AUD' => [
            'code' => 'AUD',
            'name' => 'Australian Dollar',
            'entity' => 'COCOS (KEELING) ISLANDS (THE)',
            'numeric_code' => 36,
        ],
        'COP' => [
            'code' => 'COP',
            'name' => 'Colombian Peso',
            'entity' => 'COLOMBIA',
            'numeric_code' => 170,
        ],
        'COU' => [
            'code' => 'COU',
            'name' => 'Unidad de Valor Real',
            'entity' => 'COLOMBIA',
            'numeric_code' => 970,
        ],
        'KMF' => [
            'code' => 'KMF',
            'name' => 'Comorian Franc',
            'entity' => 'COMOROS (THE)',
            'MinorUnit' => '0',
            'numeric_code' => 174,
        ],
        'CDF' => [
            'code' => 'CDF',
            'name' => 'Congolese Franc',
            'entity' => 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
            'numeric_code' => 976,
        ],
        'XAF' => [
            'code' => 'XAF',
            'name' => 'CFA Franc BEAC',
            'entity' => 'CONGO (THE)',
            'MinorUnit' => '0',
            'numeric_code' => 950,
        ],
        'NZD' => [
            'code' => 'NZD',
            'name' => 'New Zealand Dollar',
            'entity' => 'COOK ISLANDS (THE)',
            'numeric_code' => 554,
        ],
        'CRC' => [
            'code' => 'CRC',
            'name' => 'Costa Rican Colon',
            'entity' => 'COSTA RICA',
            'numeric_code' => 188,
        ],
        'XOF' => [
            'code' => 'XOF',
            'name' => 'CFA Franc BCEAO',
            'entity' => "CÔTE D'IVOIRE",
            'MinorUnit' => '0',
            'numeric_code' => 952,
        ],
        'HRK' => [
            'code' => 'HRK',
            'name' => 'Kuna',
            'entity' => 'CROATIA',
            'numeric_code' => 191,
        ],
        'CUP' => [
            'code' => 'CUP',
            'name' => 'Cuban Peso',
            'entity' => 'CUBA',
            'numeric_code' => 192,
        ],
        'CUC' => [
            'code' => 'CUC',
            'name' => 'Peso Convertible',
            'entity' => 'CUBA',
            'numeric_code' => 931,
        ],
        'ANG' => [
            'code' => 'ANG',
            'name' => 'Netherlands Antillean Guilder',
            'entity' => 'CURAÇAO',
            'numeric_code' => 532,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'CYPRUS',
            'numeric_code' => 978,
        ],
        'CZK' => [
            'code' => 'CZK',
            'name' => 'Czech Koruna',
            'entity' => 'CZECHIA',
            'numeric_code' => 203,
        ],
        'DKK' => [
            'code' => 'DKK',
            'name' => 'Danish Krone',
            'entity' => 'DENMARK',
            'numeric_code' => 208,
        ],
        'DJF' => [
            'code' => 'DJF',
            'name' => 'Djibouti Franc',
            'entity' => 'DJIBOUTI',
            'MinorUnit' => '0',
            'numeric_code' => 262,
        ],
        'XCD' => [
            'code' => 'XCD',
            'name' => 'East Caribbean Dollar',
            'entity' => 'DOMINICA',
            'numeric_code' => 951,
        ],
        'DOP' => [
            'code' => 'DOP',
            'name' => 'Dominican Peso',
            'entity' => 'DOMINICAN REPUBLIC (THE)',
            'numeric_code' => 214,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'ECUADOR',
            'numeric_code' => 840,
        ],
        'EGP' => [
            'code' => 'EGP',
            'name' => 'Egyptian Pound',
            'entity' => 'EGYPT',
            'numeric_code' => 818,
        ],
        'SVC' => [
            'code' => 'SVC',
            'name' => 'El Salvador Colon',
            'entity' => 'EL SALVADOR',
            'numeric_code' => 222,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'EL SALVADOR',
            'numeric_code' => 840,
        ],
        'XAF' => [
            'code' => 'XAF',
            'name' => 'CFA Franc BEAC',
            'entity' => 'EQUATORIAL GUINEA',
            'MinorUnit' => '0',
            'numeric_code' => 950,
        ],
        'ERN' => [
            'code' => 'ERN',
            'name' => 'Nakfa',
            'entity' => 'ERITREA',
            'numeric_code' => 232,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'ESTONIA',
            'numeric_code' => 978,
        ],
        'SZL' => [
            'code' => 'SZL',
            'name' => 'Lilangeni',
            'entity' => 'ESWATINI',
            'numeric_code' => 748,
        ],
        'ETB' => [
            'code' => 'ETB',
            'name' => 'Ethiopian Birr',
            'entity' => 'ETHIOPIA',
            'numeric_code' => 230,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'EUROPEAN UNION',
            'numeric_code' => 978,
        ],
        'FKP' => [
            'code' => 'FKP',
            'name' => 'Falkland Islands Pound',
            'entity' => 'FALKLAND ISLANDS (THE) [MALVINAS]',
            'numeric_code' => 238,
        ],
        'DKK' => [
            'code' => 'DKK',
            'name' => 'Danish Krone',
            'entity' => 'FAROE ISLANDS (THE)',
            'numeric_code' => 208,
        ],
        'FJD' => [
            'code' => 'FJD',
            'name' => 'Fiji Dollar',
            'entity' => 'FIJI',
            'numeric_code' => 242,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'FINLAND',
            'numeric_code' => 978,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'FRANCE',
            'numeric_code' => 978,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'FRENCH GUIANA',
            'numeric_code' => 978,
        ],
        'XPF' => [
            'code' => 'XPF',
            'name' => 'CFP Franc',
            'entity' => 'FRENCH POLYNESIA',
            'MinorUnit' => '0',
            'numeric_code' => 953,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'FRENCH SOUTHERN TERRITORIES (THE)',
            'numeric_code' => 978,
        ],
        'XAF' => [
            'code' => 'XAF',
            'name' => 'CFA Franc BEAC',
            'entity' => 'GABON',
            'MinorUnit' => '0',
            'numeric_code' => 950,
        ],
        'GMD' => [
            'code' => 'GMD',
            'name' => 'Dalasi',
            'entity' => 'GAMBIA (THE)',
            'numeric_code' => 270,
        ],
        'GEL' => [
            'code' => 'GEL',
            'name' => 'Lari',
            'entity' => 'GEORGIA',
            'numeric_code' => 981,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'GERMANY',
            'numeric_code' => 978,
        ],
        'GHS' => [
            'code' => 'GHS',
            'name' => 'Ghana Cedi',
            'entity' => 'GHANA',
            'numeric_code' => 936,
        ],
        'GIP' => [
            'code' => 'GIP',
            'name' => 'Gibraltar Pound',
            'entity' => 'GIBRALTAR',
            'numeric_code' => 292,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'GREECE',
            'numeric_code' => 978,
        ],
        'DKK' => [
            'code' => 'DKK',
            'name' => 'Danish Krone',
            'entity' => 'GREENLAND',
            'numeric_code' => 208,
        ],
        'XCD' => [
            'code' => 'XCD',
            'name' => 'East Caribbean Dollar',
            'entity' => 'GRENADA',
            'numeric_code' => 951,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'GUADELOUPE',
            'numeric_code' => 978,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'GUAM',
            'numeric_code' => 840,
        ],
        'GTQ' => [
            'code' => 'GTQ',
            'name' => 'Quetzal',
            'entity' => 'GUATEMALA',
            'numeric_code' => 320,
        ],
        'GBP' => [
            'code' => 'GBP',
            'name' => 'Pound Sterling',
            'entity' => 'GUERNSEY',
            'numeric_code' => 826,
        ],
        'GNF' => [
            'code' => 'GNF',
            'name' => 'Guinean Franc',
            'entity' => 'GUINEA',
            'MinorUnit' => '0',
            'numeric_code' => 324,
        ],
        'XOF' => [
            'code' => 'XOF',
            'name' => 'CFA Franc BCEAO',
            'entity' => 'GUINEA-BISSAU',
            'MinorUnit' => '0',
            'numeric_code' => 952,
        ],
        'GYD' => [
            'code' => 'GYD',
            'name' => 'Guyana Dollar',
            'entity' => 'GUYANA',
            'numeric_code' => 328,
        ],
        'HTG' => [
            'code' => 'HTG',
            'name' => 'Gourde',
            'entity' => 'HAITI',
            'numeric_code' => 332,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'HAITI',
            'numeric_code' => 840,
        ],
        'AUD' => [
            'code' => 'AUD',
            'name' => 'Australian Dollar',
            'entity' => 'HEARD ISLAND AND McDONALD ISLANDS',
            'numeric_code' => 36,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'HOLY SEE (THE)',
            'numeric_code' => 978,
        ],
        'HNL' => [
            'code' => 'HNL',
            'name' => 'Lempira',
            'entity' => 'HONDURAS',
            'numeric_code' => 340,
        ],
        'HKD' => [
            'code' => 'HKD',
            'name' => 'Hong Kong Dollar',
            'entity' => 'HONG KONG',
            'numeric_code' => 344,
        ],
        'HUF' => [
            'code' => 'HUF',
            'name' => 'Forint',
            'entity' => 'HUNGARY',
            'numeric_code' => 348,
        ],
        'ISK' => [
            'code' => 'ISK',
            'name' => 'Iceland Krona',
            'entity' => 'ICELAND',
            'MinorUnit' => '0',
            'numeric_code' => 352,
        ],
        'INR' => [
            'code' => 'INR',
            'name' => 'Indian Rupee',
            'entity' => 'INDIA',
            'numeric_code' => 356,
        ],
        'IDR' => [
            'code' => 'IDR',
            'name' => 'Rupiah',
            'entity' => 'INDONESIA',
            'numeric_code' => 360,
        ],
        'XDR' => [
            'code' => 'XDR',
            'name' => 'SDR (Special Drawing Right)',
            'entity' => 'INTERNATIONAL MONETARY FUND (IMF)',
            'MinorUnit' => '-',
            'numeric_code' => 960,
        ],
        'IRR' => [
            'code' => 'IRR',
            'name' => 'Iranian Rial',
            'entity' => 'IRAN (ISLAMIC REPUBLIC OF)',
            'numeric_code' => 364,
        ],
        'IQD' => [
            'code' => 'IQD',
            'name' => 'Iraqi Dinar',
            'entity' => 'IRAQ',
            'MinorUnit' => '3',
            'numeric_code' => 368,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'IRELAND',
            'numeric_code' => 978,
        ],
        'GBP' => [
            'code' => 'GBP',
            'name' => 'Pound Sterling',
            'entity' => 'ISLE OF MAN',
            'numeric_code' => 826,
        ],
        'ILS' => [
            'code' => 'ILS',
            'name' => 'New Israeli Sheqel',
            'entity' => 'ISRAEL',
            'numeric_code' => 376,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'ITALY',
            'numeric_code' => 978,
        ],
        'JMD' => [
            'code' => 'JMD',
            'name' => 'Jamaican Dollar',
            'entity' => 'JAMAICA',
            'numeric_code' => 388,
        ],
        'JPY' => [
            'code' => 'JPY',
            'name' => 'Yen',
            'entity' => 'JAPAN',
            'MinorUnit' => '0',
            'numeric_code' => 392,
        ],
        'GBP' => [
            'code' => 'GBP',
            'name' => 'Pound Sterling',
            'entity' => 'JERSEY',
            'numeric_code' => 826,
        ],
        'JOD' => [
            'code' => 'JOD',
            'name' => 'Jordanian Dinar',
            'entity' => 'JORDAN',
            'MinorUnit' => '3',
            'numeric_code' => 400,
        ],
        'KZT' => [
            'code' => 'KZT',
            'name' => 'Tenge',
            'entity' => 'KAZAKHSTAN',
            'numeric_code' => 398,
        ],
        'KES' => [
            'code' => 'KES',
            'name' => 'Kenyan Shilling',
            'entity' => 'KENYA',
            'numeric_code' => 404,
        ],
        'AUD' => [
            'code' => 'AUD',
            'name' => 'Australian Dollar',
            'entity' => 'KIRIBATI',
            'numeric_code' => 36,
        ],
        'KPW' => [
            'code' => 'KPW',
            'name' => 'North Korean Won',
            'entity' => "KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)",
            'numeric_code' => 408,
        ],
        'KRW' => [
            'code' => 'KRW',
            'name' => 'Won',
            'entity' => 'KOREA (THE REPUBLIC OF)',
            'MinorUnit' => '0',
            'numeric_code' => 410,
        ],
        'KWD' => [
            'code' => 'KWD',
            'name' => 'Kuwaiti Dinar',
            'entity' => 'KUWAIT',
            'MinorUnit' => '3',
            'numeric_code' => 414,
        ],
        'KGS' => [
            'code' => 'KGS',
            'name' => 'Som',
            'entity' => 'KYRGYZSTAN',
            'numeric_code' => 417,
        ],
        'LAK' => [
            'code' => 'LAK',
            'name' => 'Lao Kip',
            'entity' => "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
            'numeric_code' => 418,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'LATVIA',
            'numeric_code' => 978,
        ],
        'LBP' => [
            'code' => 'LBP',
            'name' => 'Lebanese Pound',
            'entity' => 'LEBANON',
            'numeric_code' => 422,
        ],
        'LSL' => [
            'code' => 'LSL',
            'name' => 'Loti',
            'entity' => 'LESOTHO',
            'numeric_code' => 426,
        ],
        'ZAR' => [
            'code' => 'ZAR',
            'name' => 'Rand',
            'entity' => 'LESOTHO',
            'numeric_code' => 710,
        ],
        'LRD' => [
            'code' => 'LRD',
            'name' => 'Liberian Dollar',
            'entity' => 'LIBERIA',
            'numeric_code' => 430,
        ],
        'LYD' => [
            'code' => 'LYD',
            'name' => 'Libyan Dinar',
            'entity' => 'LIBYA',
            'MinorUnit' => '3',
            'numeric_code' => 434,
        ],
        'CHF' => [
            'code' => 'CHF',
            'name' => 'Swiss Franc',
            'entity' => 'LIECHTENSTEIN',
            'numeric_code' => 756,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'LITHUANIA',
            'numeric_code' => 978,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'LUXEMBOURG',
            'numeric_code' => 978,
        ],
        'MOP' => [
            'code' => 'MOP',
            'name' => 'Pataca',
            'entity' => 'MACAO',
            'numeric_code' => 446,
        ],
        'MKD' => [
            'code' => 'MKD',
            'name' => 'Denar',
            'entity' => 'NORTH MACEDONIA',
            'numeric_code' => 807,
        ],
        'MGA' => [
            'code' => 'MGA',
            'name' => 'Malagasy Ariary',
            'entity' => 'MADAGASCAR',
            'numeric_code' => 969,
        ],
        'MWK' => [
            'code' => 'MWK',
            'name' => 'Malawi Kwacha',
            'entity' => 'MALAWI',
            'numeric_code' => 454,
        ],
        'MYR' => [
            'code' => 'MYR',
            'name' => 'Malaysian Ringgit',
            'entity' => 'MALAYSIA',
            'numeric_code' => 458,
        ],
        'MVR' => [
            'code' => 'MVR',
            'name' => 'Rufiyaa',
            'entity' => 'MALDIVES',
            'numeric_code' => 462,
        ],
        'XOF' => [
            'code' => 'XOF',
            'name' => 'CFA Franc BCEAO',
            'entity' => 'MALI',
            'MinorUnit' => '0',
            'numeric_code' => 952,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'MALTA',
            'numeric_code' => 978,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'MARSHALL ISLANDS (THE)',
            'numeric_code' => 840,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'MARTINIQUE',
            'numeric_code' => 978,
        ],
        'MRU' => [
            'code' => 'MRU',
            'name' => 'Ouguiya',
            'entity' => 'MAURITANIA',
            'numeric_code' => 929,
        ],
        'MUR' => [
            'code' => 'MUR',
            'name' => 'Mauritius Rupee',
            'entity' => 'MAURITIUS',
            'numeric_code' => 480,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'MAYOTTE',
            'numeric_code' => 978,
        ],
        'XUA' => [
            'code' => 'XUA',
            'name' => 'ADB Unit of Account',
            'entity' => 'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP',
            'MinorUnit' => '-',
            'numeric_code' => 965,
        ],
        'MXN' => [
            'code' => 'MXN',
            'name' => 'Mexican Peso',
            'entity' => 'MEXICO',
            'numeric_code' => 484,
        ],
        'MXV' => [
            'code' => 'MXV',
            'name' => 'Mexican Unidad de Inversion (UDI)',
            'entity' => 'MEXICO',
            'numeric_code' => 979,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'MICRONESIA (FEDERATED STATES OF)',
            'numeric_code' => 840,
        ],
        'MDL' => [
            'code' => 'MDL',
            'name' => 'Moldovan Leu',
            'entity' => 'MOLDOVA (THE REPUBLIC OF)',
            'numeric_code' => 498,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'MONACO',
            'numeric_code' => 978,
        ],
        'MNT' => [
            'code' => 'MNT',
            'name' => 'Tugrik',
            'entity' => 'MONGOLIA',
            'numeric_code' => 496,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'MONTENEGRO',
            'numeric_code' => 978,
        ],
        'XCD' => [
            'code' => 'XCD',
            'name' => 'East Caribbean Dollar',
            'entity' => 'MONTSERRAT',
            'numeric_code' => 951,
        ],
        'MAD' => [
            'code' => 'MAD',
            'name' => 'Moroccan Dirham',
            'entity' => 'MOROCCO',
            'numeric_code' => 504,
        ],
        'MZN' => [
            'code' => 'MZN',
            'name' => 'Mozambique Metical',
            'entity' => 'MOZAMBIQUE',
            'numeric_code' => 943,
        ],
        'MMK' => [
            'code' => 'MMK',
            'name' => 'Kyat',
            'entity' => 'MYANMAR',
            'numeric_code' => 104,
        ],
        'NAD' => [
            'code' => 'NAD',
            'name' => 'Namibia Dollar',
            'entity' => 'NAMIBIA',
            'numeric_code' => 516,
        ],
        'ZAR' => [
            'code' => 'ZAR',
            'name' => 'Rand',
            'entity' => 'NAMIBIA',
            'numeric_code' => 710,
        ],
        'AUD' => [
            'code' => 'AUD',
            'name' => 'Australian Dollar',
            'entity' => 'NAURU',
            'numeric_code' => 36,
        ],
        'NPR' => [
            'code' => 'NPR',
            'name' => 'Nepalese Rupee',
            'entity' => 'NEPAL',
            'numeric_code' => 524,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'NETHERLANDS (THE)',
            'numeric_code' => 978,
        ],
        'XPF' => [
            'code' => 'XPF',
            'name' => 'CFP Franc',
            'entity' => 'NEW CALEDONIA',
            'MinorUnit' => '0',
            'numeric_code' => 953,
        ],
        'NZD' => [
            'code' => 'NZD',
            'name' => 'New Zealand Dollar',
            'entity' => 'NEW ZEALAND',
            'numeric_code' => 554,
        ],
        'NIO' => [
            'code' => 'NIO',
            'name' => 'Cordoba Oro',
            'entity' => 'NICARAGUA',
            'numeric_code' => 558,
        ],
        'XOF' => [
            'code' => 'XOF',
            'name' => 'CFA Franc BCEAO',
            'entity' => 'NIGER (THE)',
            'MinorUnit' => '0',
            'numeric_code' => 952,
        ],
        'NGN' => [
            'code' => 'NGN',
            'name' => 'Naira',
            'entity' => 'NIGERIA',
            'numeric_code' => 566,
        ],
        'NZD' => [
            'code' => 'NZD',
            'name' => 'New Zealand Dollar',
            'entity' => 'NIUE',
            'numeric_code' => 554,
        ],
        'AUD' => [
            'code' => 'AUD',
            'name' => 'Australian Dollar',
            'entity' => 'NORFOLK ISLAND',
            'numeric_code' => 36,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'NORTHERN MARIANA ISLANDS (THE)',
            'numeric_code' => 840,
        ],
        'NOK' => [
            'code' => 'NOK',
            'name' => 'Norwegian Krone',
            'entity' => 'NORWAY',
            'numeric_code' => 578,
        ],
        'OMR' => [
            'code' => 'OMR',
            'name' => 'Rial Omani',
            'entity' => 'OMAN',
            'MinorUnit' => '3',
            'numeric_code' => 512,
        ],
        'PKR' => [
            'code' => 'PKR',
            'name' => 'Pakistan Rupee',
            'entity' => 'PAKISTAN',
            'numeric_code' => 586,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'PALAU',
            'numeric_code' => 840,
        ],
        null => [
            'code' => null,
            'name' => 'No universal currency',
            'entity' => 'PALESTINE, STATE OF',
            'numeric_code' => null,
        ],
        'PAB' => [
            'code' => 'PAB',
            'name' => 'Balboa',
            'entity' => 'PANAMA',
            'numeric_code' => 590,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'PANAMA',
            'numeric_code' => 840,
        ],
        'PGK' => [
            'code' => 'PGK',
            'name' => 'Kina',
            'entity' => 'PAPUA NEW GUINEA',
            'numeric_code' => 598,
        ],
        'PYG' => [
            'code' => 'PYG',
            'name' => 'Guarani',
            'entity' => 'PARAGUAY',
            'MinorUnit' => '0',
            'numeric_code' => 600,
        ],
        'PEN' => [
            'code' => 'PEN',
            'name' => 'Sol',
            'entity' => 'PERU',
            'numeric_code' => 604,
        ],
        'PHP' => [
            'code' => 'PHP',
            'name' => 'Philippine Peso',
            'entity' => 'PHILIPPINES (THE)',
            'numeric_code' => 608,
        ],
        'NZD' => [
            'code' => 'NZD',
            'name' => 'New Zealand Dollar',
            'entity' => 'PITCAIRN',
            'numeric_code' => 554,
        ],
        'PLN' => [
            'code' => 'PLN',
            'name' => 'Zloty',
            'entity' => 'POLAND',
            'numeric_code' => 985,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'PORTUGAL',
            'numeric_code' => 978,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'PUERTO RICO',
            'numeric_code' => 840,
        ],
        'QAR' => [
            'code' => 'QAR',
            'name' => 'Qatari Rial',
            'entity' => 'QATAR',
            'numeric_code' => 634,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'RÉUNION',
            'numeric_code' => 978,
        ],
        'RON' => [
            'code' => 'RON',
            'name' => 'Romanian Leu',
            'entity' => 'ROMANIA',
            'numeric_code' => 946,
        ],
        'RUB' => [
            'code' => 'RUB',
            'name' => 'Russian Ruble',
            'entity' => 'RUSSIAN FEDERATION (THE)',
            'numeric_code' => 643,
        ],
        'RWF' => [
            'code' => 'RWF',
            'name' => 'Rwanda Franc',
            'entity' => 'RWANDA',
            'MinorUnit' => '0',
            'numeric_code' => 646,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'SAINT BARTHÉLEMY',
            'numeric_code' => 978,
        ],
        'SHP' => [
            'code' => 'SHP',
            'name' => 'Saint Helena Pound',
            'entity' => 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
            'numeric_code' => 654,
        ],
        'XCD' => [
            'code' => 'XCD',
            'name' => 'East Caribbean Dollar',
            'entity' => 'SAINT KITTS AND NEVIS',
            'numeric_code' => 951,
        ],
        'XCD' => [
            'code' => 'XCD',
            'name' => 'East Caribbean Dollar',
            'entity' => 'SAINT LUCIA',
            'numeric_code' => 951,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'SAINT MARTIN (FRENCH PART)',
            'numeric_code' => 978,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'SAINT PIERRE AND MIQUELON',
            'numeric_code' => 978,
        ],
        'XCD' => [
            'code' => 'XCD',
            'name' => 'East Caribbean Dollar',
            'entity' => 'SAINT VINCENT AND THE GRENADINES',
            'numeric_code' => 951,
        ],
        'WST' => [
            'code' => 'WST',
            'name' => 'Tala',
            'entity' => 'SAMOA',
            'numeric_code' => 882,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'SAN MARINO',
            'numeric_code' => 978,
        ],
        'STN' => [
            'code' => 'STN',
            'name' => 'Dobra',
            'entity' => 'SAO TOME AND PRINCIPE',
            'numeric_code' => 930,
        ],
        'SAR' => [
            'code' => 'SAR',
            'name' => 'Saudi Riyal',
            'entity' => 'SAUDI ARABIA',
            'numeric_code' => 682,
        ],
        'XOF' => [
            'code' => 'XOF',
            'name' => 'CFA Franc BCEAO',
            'entity' => 'SENEGAL',
            'MinorUnit' => '0',
            'numeric_code' => 952,
        ],
        'RSD' => [
            'code' => 'RSD',
            'name' => 'Serbian Dinar',
            'entity' => 'SERBIA',
            'numeric_code' => 941,
        ],
        'SCR' => [
            'code' => 'SCR',
            'name' => 'Seychelles Rupee',
            'entity' => 'SEYCHELLES',
            'numeric_code' => 690,
        ],
        'SLL' => [
            'code' => 'SLL',
            'name' => 'Leone',
            'entity' => 'SIERRA LEONE',
            'numeric_code' => 694,
        ],
        'SGD' => [
            'code' => 'SGD',
            'name' => 'Singapore Dollar',
            'entity' => 'SINGAPORE',
            'numeric_code' => 702,
        ],
        'ANG' => [
            'code' => 'ANG',
            'name' => 'Netherlands Antillean Guilder',
            'entity' => 'SINT MAARTEN (DUTCH PART)',
            'numeric_code' => 532,
        ],
        'XSU' => [
            'code' => 'XSU',
            'name' => 'Sucre',
            'entity' => 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"',
            'MinorUnit' => '-',
            'numeric_code' => 994,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'SLOVAKIA',
            'numeric_code' => 978,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'SLOVENIA',
            'numeric_code' => 978,
        ],
        'SBD' => [
            'code' => 'SBD',
            'name' => 'Solomon Islands Dollar',
            'entity' => 'SOLOMON ISLANDS',
            'numeric_code' => 90,
        ],
        'SOS' => [
            'code' => 'SOS',
            'name' => 'Somali Shilling',
            'entity' => 'SOMALIA',
            'numeric_code' => 706,
        ],
        'ZAR' => [
            'code' => 'ZAR',
            'name' => 'Rand',
            'entity' => 'SOUTH AFRICA',
            'numeric_code' => 710,
        ],
        null => [
            'code' => null,
            'name' => 'No universal currency',
            'entity' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
            'numeric_code' => null,
        ],
        'SSP' => [
            'code' => 'SSP',
            'name' => 'South Sudanese Pound',
            'entity' => 'SOUTH SUDAN',
            'numeric_code' => 728,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'SPAIN',
            'numeric_code' => 978,
        ],
        'LKR' => [
            'code' => 'LKR',
            'name' => 'Sri Lanka Rupee',
            'entity' => 'SRI LANKA',
            'numeric_code' => 144,
        ],
        'SDG' => [
            'code' => 'SDG',
            'name' => 'Sudanese Pound',
            'entity' => 'SUDAN (THE)',
            'numeric_code' => 938,
        ],
        'SRD' => [
            'code' => 'SRD',
            'name' => 'Surinam Dollar',
            'entity' => 'SURINAME',
            'numeric_code' => 968,
        ],
        'NOK' => [
            'code' => 'NOK',
            'name' => 'Norwegian Krone',
            'entity' => 'SVALBARD AND JAN MAYEN',
            'numeric_code' => 578,
        ],
        'SEK' => [
            'code' => 'SEK',
            'name' => 'Swedish Krona',
            'entity' => 'SWEDEN',
            'numeric_code' => 752,
        ],
        'CHF' => [
            'code' => 'CHF',
            'name' => 'Swiss Franc',
            'entity' => 'SWITZERLAND',
            'numeric_code' => 756,
        ],
        'CHE' => [
            'code' => 'CHE',
            'name' => 'WIR Euro',
            'entity' => 'SWITZERLAND',
            'numeric_code' => 947,
        ],
        'CHW' => [
            'code' => 'CHW',
            'name' => 'WIR Franc',
            'entity' => 'SWITZERLAND',
            'numeric_code' => 948,
        ],
        'SYP' => [
            'code' => 'SYP',
            'name' => 'Syrian Pound',
            'entity' => 'SYRIAN ARAB REPUBLIC',
            'numeric_code' => 760,
        ],
        'TWD' => [
            'code' => 'TWD',
            'name' => 'New Taiwan Dollar',
            'entity' => 'TAIWAN (PROVINCE OF CHINA)',
            'numeric_code' => 901,
        ],
        'TJS' => [
            'code' => 'TJS',
            'name' => 'Somoni',
            'entity' => 'TAJIKISTAN',
            'numeric_code' => 972,
        ],
        'TZS' => [
            'code' => 'TZS',
            'name' => 'Tanzanian Shilling',
            'entity' => 'TANZANIA, UNITED REPUBLIC OF',
            'numeric_code' => 834,
        ],
        'THB' => [
            'code' => 'THB',
            'name' => 'Baht',
            'entity' => 'THAILAND',
            'numeric_code' => 764,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'TIMOR-LESTE',
            'numeric_code' => 840,
        ],
        'XOF' => [
            'code' => 'XOF',
            'name' => 'CFA Franc BCEAO',
            'entity' => 'TOGO',
            'MinorUnit' => '0',
            'numeric_code' => 952,
        ],
        'NZD' => [
            'code' => 'NZD',
            'name' => 'New Zealand Dollar',
            'entity' => 'TOKELAU',
            'numeric_code' => 554,
        ],
        'TOP' => [
            'code' => 'TOP',
            'name' => "Pa'anga",
            'entity' => 'TONGA',
            'numeric_code' => 776,
        ],
        'TTD' => [
            'code' => 'TTD',
            'name' => 'Trinidad and Tobago Dollar',
            'entity' => 'TRINIDAD AND TOBAGO',
            'numeric_code' => 780,
        ],
        'TND' => [
            'code' => 'TND',
            'name' => 'Tunisian Dinar',
            'entity' => 'TUNISIA',
            'MinorUnit' => '3',
            'numeric_code' => 788,
        ],
        'TRY' => [
            'code' => 'TRY',
            'name' => 'Turkish Lira',
            'entity' => 'TURKEY',
            'numeric_code' => 949,
        ],
        'TMT' => [
            'code' => 'TMT',
            'name' => 'Turkmenistan New Manat',
            'entity' => 'TURKMENISTAN',
            'numeric_code' => 934,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'TURKS AND CAICOS ISLANDS (THE)',
            'numeric_code' => 840,
        ],
        'AUD' => [
            'code' => 'AUD',
            'name' => 'Australian Dollar',
            'entity' => 'TUVALU',
            'numeric_code' => 36,
        ],
        'UGX' => [
            'code' => 'UGX',
            'name' => 'Uganda Shilling',
            'entity' => 'UGANDA',
            'MinorUnit' => '0',
            'numeric_code' => 800,
        ],
        'UAH' => [
            'code' => 'UAH',
            'name' => 'Hryvnia',
            'entity' => 'UKRAINE',
            'numeric_code' => 980,
        ],
        'AED' => [
            'code' => 'AED',
            'name' => 'UAE Dirham',
            'entity' => 'UNITED ARAB EMIRATES (THE)',
            'numeric_code' => 784,
        ],
        'GBP' => [
            'code' => 'GBP',
            'name' => 'Pound Sterling',
            'entity' => 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
            'numeric_code' => 826,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'UNITED STATES MINOR OUTLYING ISLANDS (THE)',
            'numeric_code' => 840,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'UNITED STATES OF AMERICA (THE)',
            'numeric_code' => 840,
        ],
        'USN' => [
            'code' => 'USN',
            'name' => 'US Dollar (Next day)',
            'entity' => 'UNITED STATES OF AMERICA (THE)',
            'numeric_code' => 997,
        ],
        'UYU' => [
            'code' => 'UYU',
            'name' => 'Peso Uruguayo',
            'entity' => 'URUGUAY',
            'numeric_code' => 858,
        ],
        'UYI' => [
            'code' => 'UYI',
            'name' => 'Uruguay Peso en Unidades Indexadas (UI)',
            'entity' => 'URUGUAY',
            'MinorUnit' => '0',
            'numeric_code' => 940,
        ],
        'UYW' => [
            'code' => 'UYW',
            'name' => 'Unidad Previsional',
            'entity' => 'URUGUAY',
            'MinorUnit' => '4',
            'numeric_code' => 927,
        ],
        'UZS' => [
            'code' => 'UZS',
            'name' => 'Uzbekistan Sum',
            'entity' => 'UZBEKISTAN',
            'numeric_code' => 860,
        ],
        'VUV' => [
            'code' => 'VUV',
            'name' => 'Vatu',
            'entity' => 'VANUATU',
            'MinorUnit' => '0',
            'numeric_code' => 548,
        ],
        'VES' => [
            'code' => 'VES',
            'name' => 'Bolívar Soberano',
            'entity' => 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
            'numeric_code' => 928,
        ],
        'VND' => [
            'code' => 'VND',
            'name' => 'Dong',
            'entity' => 'VIET NAM',
            'MinorUnit' => '0',
            'numeric_code' => 704,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'VIRGIN ISLANDS (BRITISH)',
            'numeric_code' => 840,
        ],
        'USD' => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'entity' => 'VIRGIN ISLANDS (U.S.)',
            'numeric_code' => 840,
        ],
        'XPF' => [
            'code' => 'XPF',
            'name' => 'CFP Franc',
            'entity' => 'WALLIS AND FUTUNA',
            'MinorUnit' => '0',
            'numeric_code' => 953,
        ],
        'MAD' => [
            'code' => 'MAD',
            'name' => 'Moroccan Dirham',
            'entity' => 'WESTERN SAHARA',
            'numeric_code' => 504,
        ],
        'YER' => [
            'code' => 'YER',
            'name' => 'Yemeni Rial',
            'entity' => 'YEMEN',
            'numeric_code' => 886,
        ],
        'ZMW' => [
            'code' => 'ZMW',
            'name' => 'Zambian Kwacha',
            'entity' => 'ZAMBIA',
            'numeric_code' => 967,
        ],
        'ZWL' => [
            'code' => 'ZWL',
            'name' => 'Zimbabwe Dollar',
            'entity' => 'ZIMBABWE',
            'numeric_code' => 932,
        ],
        'XBA' => [
            'code' => 'XBA',
            'name' => 'Bond Markets Unit European Composite Unit (EURCO)',
            'entity' => 'ZZ01_Bond Markets Unit European_EURCO',
            'MinorUnit' => '-',
            'numeric_code' => 955,
        ],
        'XBB' => [
            'code' => 'XBB',
            'name' => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
            'entity' => 'ZZ02_Bond Markets Unit European_EMU-6',
            'MinorUnit' => '-',
            'numeric_code' => 956,
        ],
        'XBC' => [
            'code' => 'XBC',
            'name' => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
            'entity' => 'ZZ03_Bond Markets Unit European_EUA-9',
            'MinorUnit' => '-',
            'numeric_code' => 957,
        ],
        'XBD' => [
            'code' => 'XBD',
            'name' => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
            'entity' => 'ZZ04_Bond Markets Unit European_EUA-17',
            'MinorUnit' => '-',
            'numeric_code' => 958,
        ],
        'XTS' => [
            'code' => 'XTS',
            'name' => 'Codes specifically reserved for testing purposes',
            'entity' => 'ZZ06_Testing_Code',
            'MinorUnit' => '-',
            'numeric_code' => 963,
        ],
        'XXX' => [
            'code' => 'XXX',
            'name' => 'The codes assigned for transactions where no currency is involved',
            'entity' => 'ZZ07_No_Currency',
            'MinorUnit' => '-',
            'numeric_code' => 999,
        ],
        'XAU' => [
            'code' => 'XAU',
            'name' => 'Gold',
            'entity' => 'ZZ08_Gold',
            'MinorUnit' => '-',
            'numeric_code' => 959,
        ],
        'XPD' => [
            'code' => 'XPD',
            'name' => 'Palladium',
            'entity' => 'ZZ09_Palladium',
            'MinorUnit' => '-',
            'numeric_code' => 964,
        ],
        'XPT' => [
            'code' => 'XPT',
            'name' => 'Platinum',
            'entity' => 'ZZ10_Platinum',
            'MinorUnit' => '-',
            'numeric_code' => 962,
        ],
        'XAG' => [
            'code' => 'XAG',
            'name' => 'Silver',
            'entity' => 'ZZ11_Silver',
            'MinorUnit' => '-',
            'numeric_code' => 961,
        ],
        'AFA' => [
            'code' => 'AFA',
            'name' => 'Afghani',
            'entity' => 'AFGHANISTAN',
            'numeric_code' => 4,
        ],
        'FIM' => [
            'code' => 'FIM',
            'name' => 'Markka',
            'entity' => 'ÅLAND ISLANDS',
            'numeric_code' => 246,
        ],
        'ALK' => [
            'code' => 'ALK',
            'name' => 'Old Lek',
            'entity' => 'ALBANIA',
            'numeric_code' => 8,
        ],
        'ADP' => [
            'code' => 'ADP',
            'name' => 'Andorran Peseta',
            'entity' => 'ANDORRA',
            'numeric_code' => 20,
        ],
        'ESP' => [
            'code' => 'ESP',
            'name' => 'Spanish Peseta',
            'entity' => 'ANDORRA',
            'numeric_code' => 724,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'ANDORRA',
            'numeric_code' => 250,
        ],
        'AOK' => [
            'code' => 'AOK',
            'name' => 'Kwanza',
            'entity' => 'ANGOLA',
            'numeric_code' => 24,
        ],
        'AON' => [
            'code' => 'AON',
            'name' => 'New Kwanza',
            'entity' => 'ANGOLA',
            'numeric_code' => 24,
        ],
        'AOR' => [
            'code' => 'AOR',
            'name' => 'Kwanza Reajustado',
            'entity' => 'ANGOLA',
            'numeric_code' => 982,
        ],
        'ARA' => [
            'code' => 'ARA',
            'name' => 'Austral',
            'entity' => 'ARGENTINA',
            'numeric_code' => 32,
        ],
        'ARP' => [
            'code' => 'ARP',
            'name' => 'Peso Argentino',
            'entity' => 'ARGENTINA',
            'numeric_code' => 32,
        ],
        'ARY' => [
            'code' => 'ARY',
            'name' => 'Peso',
            'entity' => 'ARGENTINA',
            'numeric_code' => 32,
        ],
        'RUR' => [
            'code' => 'RUR',
            'name' => 'Russian Ruble',
            'entity' => 'ARMENIA',
            'numeric_code' => 810,
        ],
        'ATS' => [
            'code' => 'ATS',
            'name' => 'Schilling',
            'entity' => 'AUSTRIA',
            'numeric_code' => 40,
        ],
        'AYM' => [
            'code' => 'AYM',
            'name' => 'Azerbaijan Manat',
            'entity' => 'AZERBAIJAN',
            'numeric_code' => 945,
        ],
        'AZM' => [
            'code' => 'AZM',
            'name' => 'Azerbaijanian Manat',
            'entity' => 'AZERBAIJAN',
            'numeric_code' => 31,
        ],
        'RUR' => [
            'code' => 'RUR',
            'name' => 'Russian Ruble',
            'entity' => 'AZERBAIJAN',
            'numeric_code' => 810,
        ],
        'BYB' => [
            'code' => 'BYB',
            'name' => 'Belarusian Ruble',
            'entity' => 'BELARUS',
            'numeric_code' => 112,
        ],
        'BYR' => [
            'code' => 'BYR',
            'name' => 'Belarusian Ruble',
            'entity' => 'BELARUS',
            'numeric_code' => 974,
        ],
        'RUR' => [
            'code' => 'RUR',
            'name' => 'Russian Ruble',
            'entity' => 'BELARUS',
            'numeric_code' => 810,
        ],
        'BEC' => [
            'code' => 'BEC',
            'name' => 'Convertible Franc',
            'entity' => 'BELGIUM',
            'numeric_code' => 993,
        ],
        'BEF' => [
            'code' => 'BEF',
            'name' => 'Belgian Franc',
            'entity' => 'BELGIUM',
            'numeric_code' => 56,
        ],
        'BEL' => [
            'code' => 'BEL',
            'name' => 'Financial Franc',
            'entity' => 'BELGIUM',
            'numeric_code' => 992,
        ],
        'BOP' => [
            'code' => 'BOP',
            'name' => 'Peso boliviano',
            'entity' => 'BOLIVIA',
            'numeric_code' => 68,
        ],
        'BAD' => [
            'code' => 'BAD',
            'name' => 'Dinar',
            'entity' => 'BOSNIA AND HERZEGOVINA',
            'numeric_code' => 70,
        ],
        'BRB' => [
            'code' => 'BRB',
            'name' => 'Cruzeiro',
            'entity' => 'BRAZIL',
            'numeric_code' => 76,
        ],
        'BRC' => [
            'code' => 'BRC',
            'name' => 'Cruzado',
            'entity' => 'BRAZIL',
            'numeric_code' => 76,
        ],
        'BRE' => [
            'code' => 'BRE',
            'name' => 'Cruzeiro',
            'entity' => 'BRAZIL',
            'numeric_code' => 76,
        ],
        'BRN' => [
            'code' => 'BRN',
            'name' => 'New Cruzado',
            'entity' => 'BRAZIL',
            'numeric_code' => 76,
        ],
        'BRR' => [
            'code' => 'BRR',
            'name' => 'Cruzeiro Real',
            'entity' => 'BRAZIL',
            'numeric_code' => 987,
        ],
        'BGJ' => [
            'code' => 'BGJ',
            'name' => 'Lev A/52',
            'entity' => 'BULGARIA',
            'numeric_code' => 100,
        ],
        'BGK' => [
            'code' => 'BGK',
            'name' => 'Lev A/62',
            'entity' => 'BULGARIA',
            'numeric_code' => 100,
        ],
        'BGL' => [
            'code' => 'BGL',
            'name' => 'Lev',
            'entity' => 'BULGARIA',
            'numeric_code' => 100,
        ],
        'BUK' => [
            'code' => 'BUK',
            'name' => 'Kyat',
            'entity' => 'BURMA',
            'numeric_code' => 104,
        ],
        'HRD' => [
            'code' => 'HRD',
            'name' => 'Croatian Dinar',
            'entity' => 'CROATIA',
            'numeric_code' => 191,
        ],
        'HRK' => [
            'code' => 'HRK',
            'name' => 'Croatian Kuna',
            'entity' => 'CROATIA',
            'numeric_code' => 191,
        ],
        'CYP' => [
            'code' => 'CYP',
            'name' => 'Cyprus Pound',
            'entity' => 'CYPRUS',
            'numeric_code' => 196,
        ],
        'CSJ' => [
            'code' => 'CSJ',
            'name' => 'Krona A/53',
            'entity' => 'CZECHOSLOVAKIA',
            'numeric_code' => 203,
        ],
        'CSK' => [
            'code' => 'CSK',
            'name' => 'Koruna',
            'entity' => 'CZECHOSLOVAKIA',
            'numeric_code' => 200,
        ],
        'ECS' => [
            'code' => 'ECS',
            'name' => 'Sucre',
            'entity' => 'ECUADOR',
            'numeric_code' => 218,
        ],
        'ECV' => [
            'code' => 'ECV',
            'name' => 'Unidad de Valor Constante (UVC)',
            'entity' => 'ECUADOR',
            'numeric_code' => 983,
        ],
        'GQE' => [
            'code' => 'GQE',
            'name' => 'Ekwele',
            'entity' => 'EQUATORIAL GUINEA',
            'numeric_code' => 226,
        ],
        'EEK' => [
            'code' => 'EEK',
            'name' => 'Kroon',
            'entity' => 'ESTONIA',
            'numeric_code' => 233,
        ],
        'XEU' => [
            'code' => 'XEU',
            'name' => 'European Currency Unit (E.C.U)',
            'entity' => 'EUROPEAN MONETARY CO-OPERATION FUND (EMCF)',
            'numeric_code' => 954,
        ],
        'FIM' => [
            'code' => 'FIM',
            'name' => 'Markka',
            'entity' => 'FINLAND',
            'numeric_code' => 246,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'FRANCE',
            'numeric_code' => 250,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'FRENCH GUIANA',
            'numeric_code' => 250,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'FRENCH SOUTHERN TERRITORIES',
            'numeric_code' => 250,
        ],
        'GEK' => [
            'code' => 'GEK',
            'name' => 'Georgian Coupon',
            'entity' => 'GEORGIA',
            'numeric_code' => 268,
        ],
        'RUR' => [
            'code' => 'RUR',
            'name' => 'Russian Ruble',
            'entity' => 'GEORGIA',
            'numeric_code' => 810,
        ],
        'DDM' => [
            'code' => 'DDM',
            'name' => 'Mark der DDR',
            'entity' => 'GERMAN DEMOCRATIC REPUBLIC',
            'numeric_code' => 278,
        ],
        'DEM' => [
            'code' => 'DEM',
            'name' => 'Deutsche Mark',
            'entity' => 'GERMANY',
            'numeric_code' => 276,
        ],
        'GHC' => [
            'code' => 'GHC',
            'name' => 'Cedi',
            'entity' => 'GHANA',
            'numeric_code' => 288,
        ],
        'GHP' => [
            'code' => 'GHP',
            'name' => 'Ghana Cedi',
            'entity' => 'GHANA',
            'numeric_code' => 939,
        ],
        'GRD' => [
            'code' => 'GRD',
            'name' => 'Drachma',
            'entity' => 'GREECE',
            'numeric_code' => 300,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'GUADELOUPE',
            'numeric_code' => 250,
        ],
        'GNE' => [
            'code' => 'GNE',
            'name' => 'Syli',
            'entity' => 'GUINEA',
            'numeric_code' => 324,
        ],
        'GNS' => [
            'code' => 'GNS',
            'name' => 'Syli',
            'entity' => 'GUINEA',
            'numeric_code' => 324,
        ],
        'GWE' => [
            'code' => 'GWE',
            'name' => 'Guinea Escudo',
            'entity' => 'GUINEA-BISSAU',
            'numeric_code' => 624,
        ],
        'GWP' => [
            'code' => 'GWP',
            'name' => 'Guinea-Bissau Peso',
            'entity' => 'GUINEA-BISSAU',
            'numeric_code' => 624,
        ],
        'ITL' => [
            'code' => 'ITL',
            'name' => 'Italian Lira',
            'entity' => 'HOLY SEE (VATICAN CITY STATE)',
            'numeric_code' => 380,
        ],
        'ISJ' => [
            'code' => 'ISJ',
            'name' => 'Old Krona',
            'entity' => 'ICELAND',
            'numeric_code' => 352,
        ],
        'IEP' => [
            'code' => 'IEP',
            'name' => 'Irish Pound',
            'entity' => 'IRELAND',
            'numeric_code' => 372,
        ],
        'ILP' => [
            'code' => 'ILP',
            'name' => 'Pound',
            'entity' => 'ISRAEL',
            'numeric_code' => 376,
        ],
        'ILR' => [
            'code' => 'ILR',
            'name' => 'Old Shekel',
            'entity' => 'ISRAEL',
            'numeric_code' => 376,
        ],
        'ITL' => [
            'code' => 'ITL',
            'name' => 'Italian Lira',
            'entity' => 'ITALY',
            'numeric_code' => 380,
        ],
        'RUR' => [
            'code' => 'RUR',
            'name' => 'Russian Ruble',
            'entity' => 'KAZAKHSTAN',
            'numeric_code' => 810,
        ],
        'RUR' => [
            'code' => 'RUR',
            'name' => 'Russian Ruble',
            'entity' => 'KYRGYZSTAN',
            'numeric_code' => 810,
        ],
        'LAJ' => [
            'code' => 'LAJ',
            'name' => 'Pathet Lao Kip',
            'entity' => 'LAO',
            'numeric_code' => 418,
        ],
        'LVL' => [
            'code' => 'LVL',
            'name' => 'Latvian Lats',
            'entity' => 'LATVIA',
            'numeric_code' => 428,
        ],
        'LVR' => [
            'code' => 'LVR',
            'name' => 'Latvian Ruble',
            'entity' => 'LATVIA',
            'numeric_code' => 428,
        ],
        'LSM' => [
            'code' => 'LSM',
            'name' => 'Loti',
            'entity' => 'LESOTHO',
            'numeric_code' => 426,
        ],
        'ZAL' => [
            'code' => 'ZAL',
            'name' => 'Financial Rand',
            'entity' => 'LESOTHO',
            'numeric_code' => 991,
        ],
        'LTL' => [
            'code' => 'LTL',
            'name' => 'Lithuanian Litas',
            'entity' => 'LITHUANIA',
            'numeric_code' => 440,
        ],
        'LTT' => [
            'code' => 'LTT',
            'name' => 'Talonas',
            'entity' => 'LITHUANIA',
            'numeric_code' => 440,
        ],
        'LUC' => [
            'code' => 'LUC',
            'name' => 'Luxembourg Convertible Franc',
            'entity' => 'LUXEMBOURG',
            'numeric_code' => 989,
        ],
        'LUF' => [
            'code' => 'LUF',
            'name' => 'Luxembourg Franc',
            'entity' => 'LUXEMBOURG',
            'numeric_code' => 442,
        ],
        'LUL' => [
            'code' => 'LUL',
            'name' => 'Luxembourg Financial Franc',
            'entity' => 'LUXEMBOURG',
            'numeric_code' => 988,
        ],
        'MGF' => [
            'code' => 'MGF',
            'name' => 'Malagasy Franc',
            'entity' => 'MADAGASCAR',
            'numeric_code' => 450,
        ],
        'MWK' => [
            'code' => 'MWK',
            'name' => 'Kwacha',
            'entity' => 'MALAWI',
            'numeric_code' => 454,
        ],
        'MVQ' => [
            'code' => 'MVQ',
            'name' => 'Maldive Rupee',
            'entity' => 'MALDIVES',
            'numeric_code' => 462,
        ],
        'MLF' => [
            'code' => 'MLF',
            'name' => 'Mali Franc',
            'entity' => 'MALI',
            'numeric_code' => 466,
        ],
        'MTL' => [
            'code' => 'MTL',
            'name' => 'Maltese Lira',
            'entity' => 'MALTA',
            'numeric_code' => 470,
        ],
        'MTP' => [
            'code' => 'MTP',
            'name' => 'Maltese Pound',
            'entity' => 'MALTA',
            'numeric_code' => 470,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'MARTINIQUE',
            'numeric_code' => 250,
        ],
        'MRO' => [
            'code' => 'MRO',
            'name' => 'Ouguiya',
            'entity' => 'MAURITANIA',
            'numeric_code' => 478,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'MAYOTTE',
            'numeric_code' => 250,
        ],
        'MXP' => [
            'code' => 'MXP',
            'name' => 'Mexican Peso',
            'entity' => 'MEXICO',
            'numeric_code' => 484,
        ],
        'RUR' => [
            'code' => 'RUR',
            'name' => 'Russian Ruble',
            'entity' => 'MOLDOVA, REPUBLIC OF',
            'numeric_code' => 810,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'MONACO',
            'numeric_code' => 250,
        ],
        'MZE' => [
            'code' => 'MZE',
            'name' => 'Mozambique Escudo',
            'entity' => 'MOZAMBIQUE',
            'numeric_code' => 508,
        ],
        'MZM' => [
            'code' => 'MZM',
            'name' => 'Mozambique Metical',
            'entity' => 'MOZAMBIQUE',
            'numeric_code' => 508,
        ],
        'NLG' => [
            'code' => 'NLG',
            'name' => 'Netherlands Guilder',
            'entity' => 'NETHERLANDS',
            'numeric_code' => 528,
        ],
        'ANG' => [
            'code' => 'ANG',
            'name' => 'Netherlands Antillean Guilder',
            'entity' => 'NETHERLANDS ANTILLES',
            'numeric_code' => 532,
        ],
        'NIC' => [
            'code' => 'NIC',
            'name' => 'Cordoba',
            'entity' => 'NICARAGUA',
            'numeric_code' => 558,
        ],
        'PEH' => [
            'code' => 'PEH',
            'name' => 'Sol',
            'entity' => 'PERU',
            'numeric_code' => 604,
        ],
        'PEI' => [
            'code' => 'PEI',
            'name' => 'Inti',
            'entity' => 'PERU',
            'numeric_code' => 604,
        ],
        'PEN' => [
            'code' => 'PEN',
            'name' => 'Nuevo Sol',
            'entity' => 'PERU',
            'numeric_code' => 604,
        ],
        'PES' => [
            'code' => 'PES',
            'name' => 'Sol',
            'entity' => 'PERU',
            'numeric_code' => 604,
        ],
        'PLZ' => [
            'code' => 'PLZ',
            'name' => 'Zloty',
            'entity' => 'POLAND',
            'numeric_code' => 616,
        ],
        'PTE' => [
            'code' => 'PTE',
            'name' => 'Portuguese Escudo',
            'entity' => 'PORTUGAL',
            'numeric_code' => 620,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'RÉUNION',
            'numeric_code' => 250,
        ],
        'ROK' => [
            'code' => 'ROK',
            'name' => 'Leu A/52',
            'entity' => 'ROMANIA',
            'numeric_code' => 642,
        ],
        'ROL' => [
            'code' => 'ROL',
            'name' => 'Old Leu',
            'entity' => 'ROMANIA',
            'numeric_code' => 642,
        ],
        'RON' => [
            'code' => 'RON',
            'name' => 'New Romanian Leu',
            'entity' => 'ROMANIA',
            'numeric_code' => 946,
        ],
        'RUR' => [
            'code' => 'RUR',
            'name' => 'Russian Ruble',
            'entity' => 'RUSSIAN FEDERATION',
            'numeric_code' => 810,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'SAINT MARTIN',
            'numeric_code' => 250,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'SAINT PIERRE AND MIQUELON',
            'numeric_code' => 250,
        ],
        'FRF' => [
            'code' => 'FRF',
            'name' => 'French Franc',
            'entity' => 'SAINT-BARTHÉLEMY',
            'numeric_code' => 250,
        ],
        'ITL' => [
            'code' => 'ITL',
            'name' => 'Italian Lira',
            'entity' => 'SAN MARINO',
            'numeric_code' => 380,
        ],
        'STD' => [
            'code' => 'STD',
            'name' => 'Dobra',
            'entity' => 'SAO TOME AND PRINCIPE',
            'numeric_code' => 678,
        ],
        'CSD' => [
            'code' => 'CSD',
            'name' => 'Serbian Dinar',
            'entity' => 'SERBIA AND MONTENEGRO',
            'numeric_code' => 891,
        ],
        'EUR' => [
            'code' => 'EUR',
            'name' => 'Euro',
            'entity' => 'SERBIA AND MONTENEGRO',
            'numeric_code' => 978,
        ],
        'SKK' => [
            'code' => 'SKK',
            'name' => 'Slovak Koruna',
            'entity' => 'SLOVAKIA',
            'numeric_code' => 703,
        ],
        'SIT' => [
            'code' => 'SIT',
            'name' => 'Tolar',
            'entity' => 'SLOVENIA',
            'numeric_code' => 705,
        ],
        'ZAL' => [
            'code' => 'ZAL',
            'name' => 'Financial Rand',
            'entity' => 'SOUTH AFRICA',
            'numeric_code' => 991,
        ],
        'SDG' => [
            'code' => 'SDG',
            'name' => 'Sudanese Pound',
            'entity' => 'SOUTH SUDAN',
            'numeric_code' => 938,
        ],
        'RHD' => [
            'code' => 'RHD',
            'name' => 'Rhodesian Dollar',
            'entity' => 'SOUTHERN RHODESIA',
            'numeric_code' => 716,
        ],
        'ESA' => [
            'code' => 'ESA',
            'name' => 'Spanish Peseta',
            'entity' => 'SPAIN',
            'numeric_code' => 996,
        ],
        'ESB' => [
            'code' => 'ESB',
            'name' => '"A" Account (convertible Peseta Account)',
            'entity' => 'SPAIN',
            'numeric_code' => 995,
        ],
        'ESP' => [
            'code' => 'ESP',
            'name' => 'Spanish Peseta',
            'entity' => 'SPAIN',
            'numeric_code' => 724,
        ],
        'SDD' => [
            'code' => 'SDD',
            'name' => 'Sudanese Dinar',
            'entity' => 'SUDAN',
            'numeric_code' => 736,
        ],
        'SDP' => [
            'code' => 'SDP',
            'name' => 'Sudanese Pound',
            'entity' => 'SUDAN',
            'numeric_code' => 736,
        ],
        'SRG' => [
            'code' => 'SRG',
            'name' => 'Surinam Guilder',
            'entity' => 'SURINAME',
            'numeric_code' => 740,
        ],
        'SZL' => [
            'code' => 'SZL',
            'name' => 'Lilangeni',
            'entity' => 'SWAZILAND',
            'numeric_code' => 748,
        ],
        'CHC' => [
            'code' => 'CHC',
            'name' => 'WIR Franc (for electronic)',
            'entity' => 'SWITZERLAND',
            'numeric_code' => 948,
        ],
        'RUR' => [
            'code' => 'RUR',
            'name' => 'Russian Ruble',
            'entity' => 'TAJIKISTAN',
            'numeric_code' => 810,
        ],
        'TJR' => [
            'code' => 'TJR',
            'name' => 'Tajik Ruble',
            'entity' => 'TAJIKISTAN',
            'numeric_code' => 762,
        ],
        'IDR' => [
            'code' => 'IDR',
            'name' => 'Rupiah',
            'entity' => 'TIMOR-LESTE',
            'numeric_code' => 360,
        ],
        'TPE' => [
            'code' => 'TPE',
            'name' => 'Timor Escudo',
            'entity' => 'TIMOR-LESTE',
            'numeric_code' => 626,
        ],
        'TRL' => [
            'code' => 'TRL',
            'name' => 'Old Turkish Lira',
            'entity' => 'TURKEY',
            'numeric_code' => 792,
        ],
        'TRY' => [
            'code' => 'TRY',
            'name' => 'New Turkish Lira',
            'entity' => 'TURKEY',
            'numeric_code' => 949,
        ],
        'RUR' => [
            'code' => 'RUR',
            'name' => 'Russian Ruble',
            'entity' => 'TURKMENISTAN',
            'numeric_code' => 810,
        ],
        'TMM' => [
            'code' => 'TMM',
            'name' => 'Turkmenistan Manat',
            'entity' => 'TURKMENISTAN',
            'numeric_code' => 795,
        ],
        'UGS' => [
            'code' => 'UGS',
            'name' => 'Uganda Shilling',
            'entity' => 'UGANDA',
            'numeric_code' => 800,
        ],
        'UGW' => [
            'code' => 'UGW',
            'name' => 'Old Shilling',
            'entity' => 'UGANDA',
            'numeric_code' => 800,
        ],
        'UAK' => [
            'code' => 'UAK',
            'name' => 'Karbovanet',
            'entity' => 'UKRAINE',
            'numeric_code' => 804,
        ],
        'SUR' => [
            'code' => 'SUR',
            'name' => 'Rouble',
            'entity' => 'UNION OF SOVIET SOCIALIST REPUBLICS',
            'numeric_code' => 810,
        ],
        'USS' => [
            'code' => 'USS',
            'name' => 'US Dollar (Same day)',
            'entity' => 'UNITED STATES',
            'numeric_code' => 998,
        ],
        'UYN' => [
            'code' => 'UYN',
            'name' => 'Old Uruguay Peso',
            'entity' => 'URUGUAY',
            'numeric_code' => 858,
        ],
        'UYP' => [
            'code' => 'UYP',
            'name' => 'Uruguayan Peso',
            'entity' => 'URUGUAY',
            'numeric_code' => 858,
        ],
        'RUR' => [
            'code' => 'RUR',
            'name' => 'Russian Ruble',
            'entity' => 'UZBEKISTAN',
            'numeric_code' => 810,
        ],
        'VEB' => [
            'code' => 'VEB',
            'name' => 'Bolivar',
            'entity' => 'VENEZUELA',
            'numeric_code' => 862,
        ],
        'VEF' => [
            'code' => 'VEF',
            'name' => 'Bolivar Fuerte',
            'entity' => 'VENEZUELA',
            'numeric_code' => 937,
        ],
        'VEF' => [
            'code' => 'VEF',
            'name' => 'Bolivar',
            'entity' => 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
            'numeric_code' => 937,
        ],
        'VEF' => [
            'code' => 'VEF',
            'name' => 'Bolívar',
            'entity' => 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
            'numeric_code' => 937,
        ],
        'VNC' => [
            'code' => 'VNC',
            'name' => 'Old Dong',
            'entity' => 'VIETNAM',
            'numeric_code' => 704,
        ],
        'YDD' => [
            'code' => 'YDD',
            'name' => 'Yemeni Dinar',
            'entity' => 'YEMEN, DEMOCRATIC',
            'numeric_code' => 720,
        ],
        'YUD' => [
            'code' => 'YUD',
            'name' => 'New Yugoslavian Dinar',
            'entity' => 'YUGOSLAVIA',
            'numeric_code' => 890,
        ],
        'YUM' => [
            'code' => 'YUM',
            'name' => 'New Dinar',
            'entity' => 'YUGOSLAVIA',
            'numeric_code' => 891,
        ],
        'YUN' => [
            'code' => 'YUN',
            'name' => 'Yugoslavian Dinar',
            'entity' => 'YUGOSLAVIA',
            'numeric_code' => 890,
        ],
        'ZRN' => [
            'code' => 'ZRN',
            'name' => 'New Zaire',
            'entity' => 'ZAIRE',
            'numeric_code' => 180,
        ],
        'ZRZ' => [
            'code' => 'ZRZ',
            'name' => 'Zaire',
            'entity' => 'ZAIRE',
            'numeric_code' => 180,
        ],
        'ZMK' => [
            'code' => 'ZMK',
            'name' => 'Zambian Kwacha',
            'entity' => 'ZAMBIA',
            'numeric_code' => 894,
        ],
        'ZWC' => [
            'code' => 'ZWC',
            'name' => 'Rhodesian Dollar',
            'entity' => 'ZIMBABWE',
            'numeric_code' => 716,
        ],
        'ZWD' => [
            'code' => 'ZWD',
            'name' => 'Zimbabwe Dollar (old)',
            'entity' => 'ZIMBABWE',
            'numeric_code' => 716,
        ],
        'ZWD' => [
            'code' => 'ZWD',
            'name' => 'Zimbabwe Dollar',
            'entity' => 'ZIMBABWE',
            'numeric_code' => 716,
        ],
        'ZWN' => [
            'code' => 'ZWN',
            'name' => 'Zimbabwe Dollar (new)',
            'entity' => 'ZIMBABWE',
            'numeric_code' => 942,
        ],
        'ZWR' => [
            'code' => 'ZWR',
            'name' => 'Zimbabwe Dollar',
            'entity' => 'ZIMBABWE',
            'numeric_code' => 935,
        ],
        'XFO' => [
            'code' => 'XFO',
            'name' => 'Gold-Franc',
            'entity' => 'ZZ01_Gold-Franc',
            'numeric_code' => null,
        ],
        'XRE' => [
            'code' => 'XRE',
            'name' => 'RINET Funds Code',
            'entity' => 'ZZ02_RINET Funds Code',
            'numeric_code' => null,
        ],
        'XFU' => [
            'code' => 'XFU',
            'name' => 'UIC-Franc',
            'entity' => 'ZZ05_UIC-Franc',
            'numeric_code' => null,
        ],
    ];

    public static function current()
    {
        return 'BDT';
    }

    public static function numericCode(string $code): int
    {
        return static::$currencies[$code]['numeric_code'];
    }
}
